apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: notification-job-prod
  namespace: argocd
spec:
  project: prod
  source:
    repoURL: https://github.com/itxcrusher/busibeez-devops.git
    targetRevision: main
    path: helm-charts/jobs
    helm:
      valueFiles:
        - ../../values/jobs/notification-job.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
