apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promotions-job
  namespace: argocd
spec:
  project: dev
  source:
    repoURL: https://github.com/itxcrusher/busibeez-devops.git
    targetRevision: dev
    path: helm-charts/jobs
    helm:
      valueFiles:
        - ../../values/jobs/promotions-job.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
