apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd
spec:
  project: dev
  source:
    repoURL: https://github.com/BusiBeez/busibeez-devops.git
    targetRevision: dev
    path: helm-charts/elk/elasticsearch
    helm:
      valueFiles:
        - ../../values/elk/elasticsearch.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
