apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.serviceName | default .Chart.Name }}
  labels:
    app: {{ .Values.serviceName | default .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.serviceName | default .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.serviceName | default .Chart.Name }}
    spec:
      containers:
        - name: {{ .Values.serviceName | default .Chart.Name }}-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: SOCKET_PORT
              value: "{{ .Values.service.port }}"
          resources:
{{ toYaml .Values.resources | indent 12 }}
      imagePullSecrets:
        - name: gitlab-registry
