replicaCount: 1

image:
  repository: registry.gitlab.com/astutexdevops/bb-latest/<SERVICE_NAME>
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: nginx
  hosts: []  # Override in environment-specific values
  tls:
    - secretName: placeholder-tls-secret
      hosts: []

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  cpuUtilizationPercentage: 80
