{{- range .Values.jobApps }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}-job
  namespace: argocd
spec:
  project: {{ $.Values.project }}
  source:
    repoURL: https://github.com/itxcrusher/busibeez-devops.git
    targetRevision: {{ $.Values.branch }}
    path: helm-charts/jobs
    helm:
      valueFiles:
        - ../../values/jobs/{{ .name }}.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ $.Values.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
{{- end }}
