apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .Values.project }}
  namespace: argocd
spec:
  description: Project for {{ .Values.branch }} environment
  sourceRepos:
    - {{ .Values.repoURL }}
  destinations:
    - namespace: {{ .Values.namespace }}
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
