apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dev-cert
  namespace: dev
spec:
  secretName: dev-tls-secret
  issuerRef:
    name: letsencrypt-cert
    kind: ClusterIssuer
  dnsNames:
    - sandbox.busibeez.com
  duration: 2160h
  renewBefore: 360h
  privateKey:
    algorithm: RSA
    size: 2048
