replicaCount: 2

image:
  tag: prod

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: busibeez.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: letsencrypt-prod-cert
      hosts:
        - busibeez.com

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  cpuUtilizationPercentage: 75
