apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: busibeez-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/itxcrusher/busibeez-devops.git  # Update here if needed
    targetRevision: HEAD
    path: argocd/applications
  destination:
    server: https://kubernetes.default.svc   # Change this if deploying to an external cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
