apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: busibeez-dev-apps
  namespace: argocd
spec:
  project: dev
  source:
    repoURL: https://github.com/itxcrusher/busibeez-devops.git
    targetRevision: dev
    path: argocd/apps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
