apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-cert
  namespace: ssl             # Updated namespace
spec:
  secretName: letsencrypt-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - dev.busibeez.com
    - test.busibeez.com
    - busibeez.com
    - argocd.busibeez.com
    - dashboard.busibeez.com
  duration: 2160h         # 90 days
  renewBefore: 360h       # 15 days before expiry
  privateKey:
    algorithm: RSA
    size: 2048
