apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.serviceName | default .Chart.Name }}
  labels:
    app: {{ .Values.serviceName | default .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.serviceName | default .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.serviceName | default .Chart.Name }}
    spec:
      containers:
      - name: {{ .Values.serviceName | default .Chart.Name }}-container
        image: "registry.gitlab.com/astutexdevops/bb-latest/{{ .Values.serviceName | default .Chart.Name }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - containerPort: {{ .Values.service.port }}
        env:
          {{- range .Values.env }}
          - name: {{ .name }}
            value: "{{ .value }}"
          {{- end }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
      imagePullSecrets:
        - name: gitlab-registry
