{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.serviceName }}-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-cert"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/client-max-body-size: "100m"
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    {{- range .Values.ingress.tls }}
    - secretName: {{ .secretName }}
      hosts:
        {{- range .hosts }}
        - {{ . }}
        {{- end }}
    {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          - path: "{{ if eq $.Values.serviceName "app" }}/(|$)(.*){{ else }}/{{ $.Values.serviceName }}(/|$)(.*){{ end }}"
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $.Values.serviceName }}-svc
                port:
                  number: {{ $.Values.service.port }}
    {{- end }}
{{- end }}
