apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-sockets
  namespace: argocd
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/itxcrusher/busibeez-devops.git
    targetRevision: dev
    path: helm-charts/sockets
    helm:
      valueFiles:
        - ../../environments/dev/sockets-values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true  # If namespace may not exist
      - ApplyOutOfSyncOnly=true  # Skip syncing up-to-date resources