apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-jobs
  namespace: argocd
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/itxcrusher/busibeez-devops.git
    targetRevision: HEAD
    path: helm-charts/jobs
    helm:
      valueFiles:
        - ../../environments/prod/jobs-values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
