apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-api
  namespace: argocd
spec:
  destination:
    namespace: test
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/itxcrusher/busibeez-devops.git
    targetRevision: HEAD
    path: helm-charts/api
    helm:
      valueFiles:
        - ../../environments/test/api-values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
