apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api
  namespace: argocd
spec:
  project: {{ .Values.project }}
  source:
    repoURL: https://github.com/itxcrusher/busibeez-devops.git
    targetRevision: {{ .Values.branch }}
    path: helm-charts/apis
    helm:
      valueFiles:
        - values/apis/app.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
