replicaCount: 1

image:
  repository: registry.gitlab.com/astutexdevops/bb-latest/<SERVICE_NAME>
  tag: latest
  pullPolicy: Always

# Default schedule (can override)
schedule: "0 */6 * * *"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

configmap:
  ENVIRONMENT: "{{ .Release.Namespace }}"
